export const CARD_COLORS = ['#9ca3af', '#ffffff', '#4ca9ff', '#b780ff', '#ffb344', '#64748b'];
export const CARD_NAMES = ['Common', 'Uncommon', 'Rare', 'Epic', 'Legendary', 'Unrevealed'];
export const CARD_OPACITY = ['0', '0', '.28', '.48', '.68', '0'];
export const CARD_DEFS = '<defs><linearGradient id="metal" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#fff" stop-opacity=".8"/><stop offset=".22" stop-color="currentColor"/><stop offset=".52" stop-color="#11131c"/><stop offset=".74" stop-color="currentColor"/><stop offset="1" stop-color="#fff" stop-opacity=".65"/></linearGradient><linearGradient id="foil" x1="0" y1="0" x2="1" y2=".35"><stop stop-color="#fff" stop-opacity="0"/><stop offset=".3" stop-color="#fff" stop-opacity="0"/><stop offset=".4" stop-color="#bba0ff" stop-opacity=".7"/><stop offset=".46" stop-color="#8ee8ff"/><stop offset=".51" stop-color="#ffe99b" stop-opacity=".85"/><stop offset=".58" stop-color="#db9bff" stop-opacity=".7"/><stop offset=".7" stop-color="#fff" stop-opacity="0"/><stop offset="1" stop-color="#fff" stop-opacity="0"/></linearGradient><linearGradient id="label" x2="0" y2="1"><stop stop-color="#111824"/><stop offset="1" stop-color="#070b11"/></linearGradient><filter id="edgeGlow" x="-25%" y="-25%" width="150%" height="150%" color-interpolation-filters="sRGB"><feGaussianBlur stdDeviation="5"/></filter><clipPath id="artClip"><rect x="16" y="16" width="480" height="496" rx="4"/></clipPath></defs>';
export const CARD_FOIL = '<g data-finish="holographic" clip-path="url(#artClip)"><rect x="16" y="16" width="480" height="496" fill="url(#foil)"/><path d="M18 24v478h476" fill="none" stroke="currentColor" stroke-width="22" filter="url(#edgeGlow)"/></g><rect x="12" y="12" width="488" height="560" rx="10" fill="none" stroke="currentColor" stroke-width="12" filter="url(#edgeGlow)"/>';
export const CARD_BORDER = '<path d="M8 512h496v64H8z" fill="url(#label)"/><rect x="10" y="10" width="492" height="564" rx="10" fill="none" stroke="#080a10" stroke-width="16"/><rect x="10" y="10" width="492" height="564" rx="10" fill="none" stroke="url(#metal)" stroke-width="10"/><rect x="16" y="16" width="480" height="552" rx="4" fill="none" stroke="currentColor" stroke-width="3"/><path d="M21 503V21h470" fill="none" stroke="#fff" stroke-opacity=".4" stroke-width="2"/><path d="M16 512h480" stroke="currentColor" stroke-width="6"/>';
export function cardFrame(rarity) {
  const r = rarity >= 0 && rarity < 6 ? rarity : 0;
  return `<g color="${CARD_COLORS[r]}" shape-rendering="geometricPrecision">${CARD_DEFS}${r >= 2 && r <= 4 ? `<g opacity="${CARD_OPACITY[r]}">${CARD_FOIL}</g>` : ''}${CARD_BORDER}<text x="256" y="554" text-anchor="middle" font-family="Arial,sans-serif" font-size="28" font-weight="800" letter-spacing="2" fill="currentColor">${CARD_NAMES[r]}</text></g>`;
}
