export const RC = ['0000000000000001', '0000000000008082', '800000000000808a', '8000000080008000', '000000000000808b', '0000000080000001', '8000000080008081', '8000000000008009', '000000000000008a', '0000000000000088', '0000000080008009', '000000008000000a', '000000008000808b', '800000000000008b', '8000000000008089', '8000000000008003', '8000000000008002', '8000000000000080', '000000000000800a', '800000008000000a', '8000000080008081', '8000000000008080', '0000000080000001', '8000000080008008'];
export const PI = [10, 7, 11, 17, 18, 3, 5, 16, 8, 21, 24, 4, 15, 23, 19, 13, 12, 2, 20, 14, 22, 9, 6, 1];
export const ROT = [1, 3, 6, 10, 15, 21, 28, 36, 45, 55, 2, 14, 27, 41, 56, 8, 25, 43, 62, 18, 39, 61, 20, 44];
export function gpuShader() {
  const s = ['// Generated by scripts/build-miner.mjs. Fixed lane indices keep state in registers.', 'struct Params { words:array<u32,32> }; struct Record { hash:array<u32,8>, offset:u32, valid:u32 };', '@group(0) @binding(0) var<storage,read> params:Params; @group(0) @binding(1) var<storage,read_write> records:array<Record>; @group(0) @binding(2) var<storage,read_write> result:array<Record>;', 'var<workgroup> partials:array<Record,64>;', `const RC=array<vec2<u32>,24>(${RC.map(h => `vec2(0x${h.slice(8)}u,0x${h.slice(0, 8)}u)`).join(',')});`, 'fn rol(v:vec2<u32>,n:u32)->vec2<u32>{if(n<32u){return (v<<vec2(n))|(v.yx>>vec2(32u-n));}let k=n-32u;return (v.yx<<vec2(k))|(v>>vec2(32u-k));}', 'fn swap(v:u32)->u32{return (v>>24u)|((v>>8u)&0xff00u)|((v<<8u)&0xff0000u)|(v<<24u);}', 'fn less(a:Record,b:Record)->bool{if(a.valid==0u){return false;}if(b.valid==0u){return true;}', ...Array.from({
    length: 8
  }, (_, i) => `if(a.hash[${i}]!=b.hash[${i}]){return a.hash[${i}]<b.hash[${i}];}`), 'return a.offset<b.offset;}', 'fn hashAt(index:u32)->Record{let lo=params.words[29]+index;let hi=params.words[30]+select(0u,1u,lo<params.words[29]);'];
  for (let i = 0; i < 25; i++) s.push(`var a${i}=${i < 14 ? `vec2(params.words[${2 * i}],params.words[${2 * i + 1}])` : i === 14 ? 'vec2(params.words[28],1u)' : i === 16 ? 'vec2(0u,0x80000000u)' : 'vec2(0u)'};`);
  s.push('a5.y=swap(hi);a6.x=swap(lo);for(var round=0u;round<24u;round++){');
  for (let x = 0; x < 5; x++) s.push(`let c${x}=${Array.from({
    length: 5
  }, (_, y) => `a${x + 5 * y}`).join('^')};`);
  for (let x = 0; x < 5; x++) s.push(`let d${x}=c${(x + 4) % 5}^rol(c${(x + 1) % 5},1u);${Array.from({
    length: 5
  }, (_, y) => `a${x + 5 * y}^=d${x};`).join('')}`);
  s.push('var t=a1;var u=vec2(0u);');
  for (let i = 0; i < 24; i++) s.push(`u=a${PI[i]};a${PI[i]}=rol(t,${ROT[i]}u);t=u;`);
  for (let y = 0; y < 5; y++) {
    s.push('{');
    for (let x = 0; x < 5; x++) s.push(`let b${x}=a${y * 5 + x};`);
    for (let x = 0; x < 5; x++) s.push(`a${y * 5 + x}=b${x}^((~b${(x + 1) % 5})&b${(x + 2) % 5});`);
    s.push('}');
  }
  s.push('a0^=RC[round];}', `return Record(array<u32,8>(${Array.from({
    length: 8
  }, (_, i) => `swap(a${Math.floor(i / 2)}.${i % 2 ? 'y' : 'x'})`).join(',')}),index,1u);}`);
  const reduction = 'workgroupBarrier();for(var stride=32u;stride>0u;stride>>=1u){if(lid<stride){let other=partials[lid+stride];if(less(other,partials[lid])){partials[lid]=other;}}workgroupBarrier();}';
  s.push('@compute @workgroup_size(64) fn main(@builtin(global_invocation_id) gid:vec3<u32>,@builtin(local_invocation_index) lid:u32,@builtin(workgroup_id) group:vec3<u32>){var best:Record;for(var j=0u;j<8u;j++){let index=gid.x*8u+j;if(index<params.words[31]){let candidate=hashAt(index);if(less(candidate,best)){best=candidate;}}}partials[lid]=best;', reduction, 'if(lid==0u){records[group.x]=partials[0];}}');
  s.push('@compute @workgroup_size(64) fn reduce(@builtin(local_invocation_index) lid:u32){var best:Record;let count=(params.words[31]+511u)/512u;for(var i=lid;i<count;i+=64u){let candidate=records[i];if(less(candidate,best)){best=candidate;}}partials[lid]=best;', reduction, 'if(lid==0u){result[0]=partials[0];}}');
  return s.join('\n') + '\n';
}
export function cpuWAT() {
  const s = ['(module (memory (export "memory") 1)', '(func $swap (param $v i64) (result i64) (local $t i64)', '(local.set $t (i64.or (i64.shl (i64.and (local.get $v) (i64.const 0x00ff00ff00ff00ff)) (i64.const 8)) (i64.and (i64.shr_u (local.get $v) (i64.const 8)) (i64.const 0x00ff00ff00ff00ff))))', '(local.set $t (i64.or (i64.shl (i64.and (local.get $t) (i64.const 0x0000ffff0000ffff)) (i64.const 16)) (i64.and (i64.shr_u (local.get $t) (i64.const 16)) (i64.const 0x0000ffff0000ffff)))) (i64.rotl (local.get $t) (i64.const 32)))', '(func (export "scan") (param $nonce i64) (param $step i64) (param $count i32) (result i32)', '(local $i i32)(local $round i32)(local $t i64)(local $u i64)(local $bestNonce i64)', ...Array.from({
    length: 25
  }, (_, i) => `(local $a${i} i64)`), ...Array.from({
    length: 5
  }, (_, i) => `(local $c${i} i64)`), ...Array.from({
    length: 4
  }, (_, i) => `(local $h${i} i64)(local $best${i} i64)`), ...Array.from({
    length: 4
  }, (_, i) => `(local.set $best${i} (i64.const -1))`), '(local.set $bestNonce (local.get $nonce))', '(block $done (br_if $done (i32.eqz (local.get $count))) (loop $scan'];
  for (let i = 0; i < 25; i++) s.push(`(local.set $a${i} ${i < 17 ? `(i64.load (i32.const ${i * 8}))` : '(i64.const 0)'})`);
  s.push('(local.set $t (call $swap (local.get $nonce)))', '(local.set $a5 (i64.or (i64.and (local.get $a5) (i64.const 0xffffffff)) (i64.shl (local.get $t) (i64.const 32))))', '(local.set $a6 (i64.or (i64.and (local.get $a6) (i64.const 0xffffffff00000000)) (i64.shr_u (local.get $t) (i64.const 32))))', '(local.set $round (i32.const 0))(loop $rounds');
  const xor = values => values.length === 1 ? values[0] : `(i64.xor ${values[0]} ${xor(values.slice(1))})`;
  for (let x = 0; x < 5; x++) s.push(`(local.set $c${x} ${xor(Array.from({
    length: 5
  }, (_, y) => `(local.get $a${x + 5 * y})`))})`);
  for (let x = 0; x < 5; x++) {
    s.push(`(local.set $t (i64.xor (local.get $c${(x + 4) % 5}) (i64.rotl (local.get $c${(x + 1) % 5}) (i64.const 1))))`);
    for (let y = 0; y < 5; y++) s.push(`(local.set $a${x + 5 * y} (i64.xor (local.get $a${x + 5 * y}) (local.get $t)))`);
  }
  s.push('(local.set $t (local.get $a1))');
  for (let i = 0; i < 24; i++) s.push(`(local.set $u (local.get $a${PI[i]}))(local.set $a${PI[i]} (i64.rotl (local.get $t) (i64.const ${ROT[i]})))(local.set $t (local.get $u))`);
  for (let y = 0; y < 5; y++) {
    for (let x = 0; x < 5; x++) s.push(`(local.set $c${x} (local.get $a${y * 5 + x}))`);
    for (let x = 0; x < 5; x++) s.push(`(local.set $a${y * 5 + x} (i64.xor (local.get $c${x}) (i64.and (i64.xor (local.get $c${(x + 1) % 5}) (i64.const -1)) (local.get $c${(x + 2) % 5}))))`);
  }
  s.push('(local.set $a0 (i64.xor (local.get $a0) (i64.load (i32.add (i32.const 512) (i32.shl (local.get $round) (i32.const 3))))))', '(local.set $round (i32.add (local.get $round) (i32.const 1)))(br_if $rounds (i32.lt_u (local.get $round) (i32.const 24))))', ...Array.from({
    length: 4
  }, (_, i) => `(local.set $h${i} (call $swap (local.get $a${i})))`));
  const less = (right, i = 0) => i === 4 ? '(i32.const 0)' : `(i32.or (i64.lt_u (local.get $h${i}) ${right(i)}) (i32.and (i64.eq (local.get $h${i}) ${right(i)}) ${less(right, i + 1)}))`;
  s.push(`(if ${less(i => `(local.get $best${i})`)} (then ${Array.from({
    length: 4
  }, (_, i) => `(local.set $best${i} (local.get $h${i}))`).join('')} (local.set $bestNonce (local.get $nonce))))`, '(local.set $i (i32.add (local.get $i) (i32.const 1)))', `(br_if $done ${less(i => `(i64.load (i32.const ${160 + i * 8}))`)})`, '(local.set $nonce (i64.add (local.get $nonce) (local.get $step)))(br_if $scan (i32.lt_u (local.get $i) (local.get $count)))))', ...Array.from({
    length: 4
  }, (_, i) => `(i64.store (i32.const ${224 + i * 8}) (local.get $best${i}))`), '(i64.store (i32.const 256) (local.get $bestNonce))(local.get $i))', `(data (i32.const 512) "${RC.map(h => h.match(/../g).reverse().map(b => '\\' + b).join('')).join('')}")`, ')');
  return s.join('\n');
}
