import React from 'react';
import { epochStart, epochSize, priceOf } from '../../shared/protocol.mjs';
import { amount, eth } from './chain.js';
export function Stats({
  state,
  config
}) {
  return <><div className="page-heading"><div><p className="eyebrow">NETWORK / ONCHAIN DATA</p><h1>Network status</h1><p>{state ? `Latest snapshot: block ${state.block.toLocaleString('en-US')}. Figures update from the connected contracts.` : 'Contracts will appear here after the verified mainnet deployment.'}</p></div></div><section className="stats-grid">{[['Foundries minted', state?.minted?.toLocaleString('en-US')], ['Foundries burned', state?.burned?.toLocaleString('en-US')], ['Eligible for rent', state?.eligible?.toLocaleString('en-US')], ['Total SCRAP supply', state ? amount(state.supply) : null], ['USDC rent funded', state ? eth(state.rentFunded) : null], ['USDC rent claimed', state ? eth(state.rentPaid) : null], ['USDC in buyback reserve', state ? eth(state.queue) : null], ['SCRAP bought and burned', state ? amount(state.burnedTokens) : null]].map(([label, value]) => <article className="panel" key={label}><span>{label}</span><strong>{value ?? '—'}</strong></article>)}</section><section className="panel"><h2>Verified deployment</h2><p>Arc Mainnet · {config?.chainId ? `Chain ID ${config.chainId}` : 'Network parameters pending'}</p><div className="address-list">{[['Collection', 'address'], ['SCRAP', 'token'], ['Liquidity hook', 'hook'], ['Swap router', 'router'], ['PoolManager', 'manager'], ['Artwork renderer', 'renderer'], ['Building artwork', 'buildings'], ['Planet artwork', 'environment'], ['Deployment factory', 'factory'], ['Owner', 'treasury'], ['Partner', 'partner']].map(([name, key]) => <div key={key}><strong>{name}</strong>{config?.[key] ? config.explorer ? <a href={`${config.explorer}/address/${config[key]}`} target="_blank" rel="noreferrer"><code>{config[key]}</code> ↗</a> : <code>{config[key]}</code> : <span>Awaiting deployment</span>}</div>)}</div>{config?.openseaUrl && <p><a href={config.openseaUrl} target="_blank" rel="noreferrer">View the collection on OpenSea ↗</a></p>}</section></>;
}
export function Economy() {
  return <><div className="page-heading"><div><p className="eyebrow">PRICES / RENT / SCRAP</p><h1>Economics</h1><p>Mint prices depend on the lifetime mint count. Burning a Foundry never restores a mint slot.</p></div></div><div className="stats-grid">{[['70%', 'USDC rent for eligible Foundries'], ['21%', 'SCRAP buyback reserve'], ['9%', 'Project allocation: 75% owner / 25% partner']].map(([v, t]) => <article className="panel" key={v}><strong>{v}</strong><p>{t}</p></article>)}</div><p>These are the normal allocations with all earlier-epoch Foundries alive. With no eligible recipients, 70% funds buybacks and 30% goes to the project. A burned recipient’s rent share is redistributed 70/21/9.</p><section className="panel"><h2>Mint epochs</h2><div className="table-scroll"><table><thead><tr><th>Epoch</th><th>Lifetime mint IDs</th><th>NFTs</th><th>USDC per mint</th></tr></thead><tbody>{Array.from({
              length: 11
            }, (_, i) => <tr key={i}><td>{i}</td><td>{String(epochStart(i))}–{String(epochStart(i) + epochSize(i) - 1n)}</td><td>{String(epochSize(i))}</td><td>{eth(priceOf(epochStart(i)))}</td></tr>)}</tbody></table></div><p>Minting continues after 16,376. A growing difficulty multiplier makes later proofs harder; there is no fixed supply cap.</p></section><div className="stats-grid"><article className="panel"><h2>Hold or burn</h2><p>Rent starts in the next mint epoch. All rarities begin at 1,000 SCRAP per burn; the reward falls smoothly by half through each later epoch. A burn requires 10 minutes and a newer mint.</p></article><article className="panel"><h2>The trading pool</h2><p>Initial liquidity: 25 USDC and 2,500,000 SCRAP. At 504 mints, the full reserve buys and burns SCRAP before trading opens. Swaps pay 5% to the owner. Buybacks are fee-free.</p></article></div><p>USDC rewards require actual mint payments. SCRAP sale proceeds depend on the pool and price impact; neither minting nor holding guarantees a return.</p><a className="button" href="#/docs">Read all protocol rules →</a></>;
}
